Alien-Worlds/eosdac-contracts

- contracts/daccustodian/daccustodian.test.ts
- contracts/daccustodian/newperiod_components.cpp
Test confirms it works without the need for code changes
> Ensure newperiod with 0 pay works

- contracts/daccustodian/daccustodian.hpp
I changed the contract name in the test file and forgot to update this header
> update MSIG_CONTRACT to match with name used in testing

- contracts/msigworlds/msigworlds.cpp
- contracts/msigworlds/msigworlds.hpp
- contracts/msigworlds/msigworlds.test.ts
The deny action unapproves the proposal if it has been approved before, does nothing otherwise.
> add deny action

- contract-shared-headers/config.hpp
- contract-shared-headers/safemath.hpp
- contracts/daccustodian/newperiod_components.cpp
- contracts/eosdactokens/eosdactokens.test.ts
- contracts/stakevote/stakevote.cpp
- contracts/stakevote/stakevote.hpp
- contracts/stakevote/stakevote.test.ts
Implement new formula for vote weight calculation
> Stakevote algo change

- contract-shared-headers/eosdactokens_shared.hpp
- contracts/daccustodian/privatehelpers.cpp
- contracts/daccustodian/voting.cpp
Valid members would mean - agreed to current member terms.
Also, there are a couple of changes to improve efficiency a little bit in the inline actions.
I tried to run the tests but had some issues of time out on lamington locally.
> Change to ensure all candidates being voted for are valid members  

- contracts/stakevote/stakevote.cpp
- contracts/stakevote/stakevote.test.ts
I haven't had any tests yet but it doesn't seem to break the existing tests.
> Remove Stake Vote rows when weight is empty

- contracts/TestHelpers.ts
- contracts/daccustodian/daccustodian.test.ts
- contracts/dacproposals/dacproposals.test.ts
- contracts/msigworlds/msigworlds.cpp
- contracts/msigworlds/msigworlds.hpp
- contracts/msigworlds/msigworlds.test.ts
Change to msigworlds that explicitly excludes the referendum contract from the membership check.
> Cu 2tzhu89 fix referendum contract to work with recent change to msigworlds

- contracts/stakevote/stakevote.cpp
- contracts/stakevote/stakevote.test.ts
This PR implements the new formula for weight_delta including tests
> Demzne 1081 eosdac implement and test new weight delta formula

- contracts/TestHelpers.ts
- contracts/daccustodian/daccustodian.test.ts
- contracts/stakevote/stakevote.test.ts
Test fixes to make sure everything works when running as submodule in alienworlds-contracts
> Demzne 1084 test fixes

- contracts/stakevote/stakevote.cpp
- contracts/stakevote/stakevote.hpp
- contracts/stakevote/stakevote.test.ts
This PR implements the formula simplifications and updates the tests.
> Demzne 1096 Simplify stakevote formula

- contract-shared-headers/daccustodian_shared.hpp
- contracts/daccustodian/daccustodian.test.ts
- contracts/daccustodian/privatehelpers.cpp
- contracts/daccustodian/voting.cpp
This introduces a new helper function to update the vote count for all candidates. It updates the vote count any time someone votes or unvotes regardless of the weight of the user.
> Demzne 1098 fix vote count

- contracts/stakevote/stakevote.cpp
- contracts/stakevote/stakevote.hpp
> Dev 2693 Set vote weight to 0 instead of asserting negative vote_weight

- contracts/msigworlds/msigworlds.cpp
This is to avoid the need to `cancel` expired proposals before they can be cleaned up.
> Allows for `cleanup` of expired MSIG proposals.

- .gitignore
- debugging/daccustodian.ipynb
- debugging/debug_daccustodian.js
- debugging/debug_stakevote.js
This PR just adds some more debugging tools
> Demzne 1209 write data analysis script to check daccustodiancandidates table

- contracts/dacproposals/dacproposals.cpp
Treat them as if they are expired proposals.
> Allow proposals to be removed if there is no associated escrow

- contracts/TestHelpers.ts
- contracts/eosdactokens/eosdactokens.cpp
- contracts/eosdactokens/eosdactokens.hpp
- contracts/eosdactokens/eosdactokens.test.ts
- package.json
Add denylist
┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/86934d9b2) by [Unito](https://www.unito.io)
> add denylist

- contracts/dacescrow/dacescrow.cpp
- contracts/dacescrow/dacescrow.hpp
- contracts/dacescrow/dacescrow_shared.hpp
- contracts/dacproposals/dacproposals.cpp
- contracts/dacproposals/dacproposals.hpp
- contracts/dacproposals/dacproposals.test.ts
┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/8693pvfk5) by [Unito](https://www.unito.io)
> Adds arbiter agreement as a requirement for each worker proposal

- contracts/dacproposals/dacproposals.cpp
- contracts/dacproposals/dacproposals.hpp
to make management easier without an API
┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/8693wt4kb) by [Unito](https://www.unito.io)
> Adds the worker proposal title and summary to the proposal table

- contract-shared-headers/daccustodian_shared.hpp
- contracts/daccustodian/config.cpp
> Demzne 3170 decentralize eosdac updateconfig action

- contracts/dacproposals/dacproposals.cpp
- contracts/dacproposals/dacproposals.hpp
- contracts/dacproposals/dacproposals.test.ts
This adds a configurable minimum proposal duration. When finalizing the proposal it is checked that the minimum proposal time has passed since the creation of the proposal.
> Demzne 3171 worker proposal minimum proposal duration

- contracts/daccustodian/daccustodian.test.ts
- contracts/daccustodian/newperiod_components.cpp
The current tests pass and I've added 2 more tests to validate a txn with double newperiod succeeds with 0 delay and fails with >0 delay
> Change the period delay check to allow for it be set to 0.

- contract-shared-headers/daccustodian_shared.hpp
- contracts/daccustodian/config.cpp
- contracts/daccustodian/daccustodian.test.ts
- contracts/daccustodian/newperiod_components.cpp
> Claim budget fixes

- contracts/dacproposals/dacproposals.cpp
- contracts/dacproposals/dacproposals.hpp
This is urgent because there is a proposal which we would like to be able to block.
It should not have been approved by the arbiter
> Add block action and state to be able quickly block a proposal that shouldn't be allowed to proceed.

- contracts/dacescrow/dacescrow.cpp
This is intended to refund an escrow after `cancelwip` of a proposal as an act of good faith to the DAO rather than waiting for expiry of the escrow.
> Extend the refund action to allow the intended receiver to refund early

- contracts/dacescrow/dacescrow.test.ts
Adds a full test-suite for the dacscrow contract
> add tests for dacescrow contract
