Alien-Worlds/eosdac-contracts

.lamingtonrc
contracts/TestHelpers.ts
contracts/daccustodian/daccustodian.test.ts
contracts/dacproposals/dacproposals.test.ts
contracts/referendum/referendum.hpp

This switches the nodeos version back to 2.0 as eosio-statereceiver which is used in the eosdac-api hasn't been updated to work with 2.1. It also makes a few small additions for covenient client testing.

Client testing

---

.clang-format
contracts/daccustodian/config.cpp
contracts/daccustodian/daccustodian.hpp
contracts/daccustodian/daccustodian.test.ts
contracts/daccustodian/newperiod_components.cpp
contracts/daccustodian/privatehelpers.cpp
contracts/daccustodian/registering.cpp
package.json

This PR intends to implement ticket "Extract the budget transfer from NewPeriod action into explicit claim action" (https://app.clickup.com/t/24ga0jf )
Remarks:
- I thought a more type-safe data format for the state2 std::map would be better, so chose to use a variant instead of int64_t to store the values. It should have minimal overhead (if at all) but it generates more reliable and more easily maintainable code IMHO.
- While working with the code, I realized we could automatically migrate the data when it's accessed for the first time. This simplifies the deployment as calling the `migratedata` action is no longer necessary. I left the migratedata action in so one can still manually migrate dacs from the outside (dacs that are inactive etc.).

Extract budget transfer

---

contract-shared-headers/common_utilities.hpp
contract-shared-headers/daccustodian_shared.hpp
contract-shared-headers/safemath.hpp
contracts/daccustodian/daccustodian.test.ts
contracts/daccustodian/privatehelpers.cpp
contracts/dacdirectory/dacdirectory.cpp
contracts/dacdirectory/dacdirectory.hpp
contracts/referendum/referendum.cpp
contracts/referendum/referendum.hpp
contracts/safemath/safemath.cpp
contracts/safemath/safemath.test.ts
contracts/stakevote/stakevote.cpp
contracts/stakevote/stakevote.hpp
contracts/stakevote/stakevote.test.ts

* Safemath: More rigoruous type checking that will catch if one tries calculations with operands of a different type
* More clever design of operators to prevent downgrade to built-in operator for number types (while still allowing implicit conversion to of S to T) for ease-of-use/convenience.
* Rewrite of safe type conversion routine `.to<type>()` based on the C++ standards support library (GSL)
* Full constexpr support for safemath, allowing to define `static constexpr` variables at compile time while at the same time allowing to perform some calculations with them at comile time.
* The above safmath changes flagged a couple of errors in the project that no longer compiled and were fixed. Where code changes were necessary, some parts of that code were also cleaned up.
* Introduction of …

safemath-improvements + related contract changes

---

contracts/msigworlds/msigworlds.cpp
contracts/msigworlds/msigworlds.hpp
contracts/msigworlds/msigworlds.test.ts

Previously all requested auths needed to be explicitly specified. 
eg. a txn for `dacaccount@active` would require `cust1@active`, `cust2@active`, `cust3@active`, `cust4@active`. 
But since the custodians could change between periods while an MSIG is still live the MSIG would need to specify cust1, cust2, cust3, cust4...cust8 to be confident to have enough auths to cover for election changes of custodians. But even then could still miss out on the required custodians to approve a txn.
* This change allows the MSIG to be proposed with the top level requested auth eg. `dacaccount@active` only so it can be dynamically checked during execution.
* Also adds a `checkauth` action that will test if the provided auths satisfy the required auth to execute the transaction. This throws an error in …

Refactor to msig.worlds to support flexible auth requests

---

contract-shared-headers/common_utilities.hpp
contract-shared-headers/daccustodian_shared.hpp
contract-shared-headers/eosdactokens_shared.hpp
contracts/daccustodian/config.cpp
contracts/daccustodian/daccustodian.test.ts
contracts/daccustodian/external_observable_actions.cpp
contracts/daccustodian/newperiod_components.cpp
contracts/daccustodian/registering.cpp

When custodian registers, validate that staketime is at least lockup_release_time_delay. Once candidate is no longer active, allow unstaking immediately. No longer rely on custodian_end_time_stamp. That field is now still present in the table, but unused.

Simplify custodian unstaking

---

contracts/daccustodian/daccustodian.test.ts
contracts/daccustodian/newperiod_components.cpp

@angelol Comments in the code will hopefully explain the intention more clearly than my previously, poorly explained attempt.
The `std::min(...)` in there previously did have some thought behind it but was clearly not thought through properly when I initially relayed it to you. 
The idea was that, when the treasury budget was low, we should transfer the total amount of treasury rather than the very long tail of 1% of an ever-decreasing amount. 
It should also only top up to that intended amount to avoid custodians hoarding the allocations across periods.
I have not unit tested this or applied any of your safe-math logic which may make this better. 
Also, please double check my logic is sound and it will never transfer the full amount of a large treasury balance.

Untested fix to the claim budget not working correctly.

---

contracts/daccustodian/daccustodian.test.ts
contracts/daccustodian/registering.cpp

fix unsigned integer wraparound below zero cause by bug that allowed candidates to be remove more than once

Cu 2u55f5t eosdac fix remove candidate action

---

contract-shared-headers/daccustodian_shared.hpp
contracts/daccustodian/daccustodian.test.ts
contracts/daccustodian/voting.cpp

Simple change, yet once thing is noteworthy. I decided to use uint8_t for the vote_count. It can only hold numbers up to 255 and will wrap around back to zero afterwards, but I think in this case, it's perfectly sufficient.

Cu 2xbq8yy add vote count to votes in daoworlds

---

contracts/daccustodian/daccustodian.test.ts
contracts/daccustodian/newperiod_components.cpp

Simplifies claimbudget calculation to always transfer the configured percentage of the treasury budget (without rounding up).

Simplify budget claim

---

contracts/daccustodian/daccustodian.test.ts

This is a small addendum to yesterday's algorithm change in the period budget. I had forgotten to commit this.

fix period budget test by rounding to 4 decimals in javascript

---

contracts/TestHelpers.ts
contracts/daccustodian/daccustodian.test.ts
contracts/dacproposals/dacproposals.test.ts
contracts/referendum/referendum.test.ts
contracts/stakevote/stakevote.test.ts

The eosdac tests assumed in many places that the issuer of tokens is always the token contract itself. The testing code was refactored to allow for setting a different token issuer and that issuer was set to an account named "federation". This now matches what is deployed on mainnet.

Refactor eosdac tests to allow token issuer that is not the token contract itself

---

contracts/daccustodian/privatehelpers.cpp

This is not strictly necessary, but could be useful to catch possible future logic errors early

add check when incrementing/decrementing number_voters 

---

contract-shared-headers/daccustodian_shared.hpp
contracts/daccustodian/daccustodian.test.ts
contracts/daccustodian/debug.cpp
contracts/daccustodian/newperiod_components.cpp
contracts/daccustodian/privatehelpers.cpp
contracts/daccustodian/registering.cpp

This was a late design request so the vote_count could be displayed per candidate - even though it's not used in the voting logic.
Also changed `total_vote_count` to `total_vote_power` to make it less ambiguous what the field means.
This change could be done without migration by taking the old/unused `custodian_end_time_stamp` and using it for `number_voters`. This worked because the size in the table is the same (uint32).

Adds number_voters to count number of voters for each candidate

---

contract-shared-headers/daccustodian_shared.hpp
contracts/daccustodian/daccustodian.test.ts
contracts/daccustodian/debug.cpp
contracts/daccustodian/privatehelpers.cpp
contracts/daccustodian/registering.cpp
contracts/daccustodian/voting.cpp

* Recycles the currently unused member `locked_tokens` of the `candidate` struct to store the `by_decayed_votes` index in a publicly visible field
* It manually call update_index where necessary. Not an ideal solution but eosio::multi_index has no way to update dependant fields or to register pre-save functions. Eosio-cpp also has c#-style properties disabled, so that can't be used either for a more elegant solution.
After deployment, the `migraterank` action needs to be called for every dac.

Demzne 1097 Make candidate ranking visible

---

.gitignore
contracts/daccustodian/newperiod_components.cpp
contracts/newperiodctl/newperiodctl.cpp
contracts/newperiodctl/newperiodctl.ts

Also changes the permission used from owner to active for better permission management.
Please check the git ignore. I changed it to ignore all files in the compiled contract rather each individual contract. Not sure if there was a reason not to do that earlier. So let me know if this should be reverted.

Adds minimal smart contract to be used for DAO activation

---

contract-shared-headers/daccustodian_shared.hpp
contracts/daccustodian/daccustodian.test.ts
contracts/daccustodian/debug.cpp
contracts/daccustodian/privatehelpers.cpp
contracts/daccustodian/voting.cpp

Just a quick additional action to remove any invalid candidates from the planets that don't have enough staked tokens already. This would force them to `nominatecane` again.

Add debug action to remove individual candidates

---

contract-shared-headers/daccustodian_shared.hpp
contracts/daccustodian/config.cpp
contracts/daccustodian/debug.cpp
contracts/daccustodian/update_member_details.cpp
contracts/eosdactokens/eosdactokens.cpp
contracts/eosdactokens/eosdactokens.hpp
contracts/stakevote/stakevote.cpp
contracts/stakevote/stakevote.hpp

These should only be callable by get_self() with the long-term intention to open these up for the DAO to call later.
In an attempt to not break all the unit tests these changes have been wrapped with `#if IS_DEV` 
I don't think these changes need unit tests to verify. I will manually test on-chain before the DAOs go live.
Also removed a couple of actions from the token contract which will create more confusion than value.
@angelol Sorry, I haven't run the unit tests on this change to be sure I haven't broken anything. But potentially something may have broken - particularly since I removed actions that may have had tests.

Adding conditional checks to to lock config focus actions

---

contract-shared-headers/eosdactokens_shared.hpp
contracts/eosdactokens/eosdactokens.cpp
contracts/eosdactokens/eosdactokens.test.ts

A common misconception (you could also call it a bug) in the way eosio::multi_index works is that contrary to primary indexes, secondary indexes don't filter out non-matching results when using find(). They only point the iterator to the first matching element. It is up to the user of the API to break the iteration once results no longer match the search criteria.

Demzne 1105 eosdac staking not working with current unstakes

---

contracts/stakevote/stakevote.cpp

This PR enables numeric checks on the vote weight and vote weight quorum updates to prevent unsigned wraparounds in the case of logic errors.

Stakevote contract enable numeric checks

---

contract-shared-headers/config.hpp
contract-shared-headers/daccustodian_shared.hpp
contracts/daccustodian/config.cpp
contracts/daccustodian/newperiod_components.cpp
contracts/daccustodian/registering.cpp
contracts/daccustodian/voting.cpp

* Blocks all proxy voting activity for now
* Adds convenience action to remove votes and nominate without pay.
* Removes unused stprofileuns action
* Sets a max limit on the size of the profile (Just an arbitrary number but this was completely open for now otherwise)
* Enables voting for all planets.
* Moves the budget configs with the other config actions.

General cleanup in Prod for dao.worlds

---

contract-shared-headers/daccustodian_shared.hpp
contracts/daccustodian/registering.cpp

This is to reduce spam opportunities on the pass-through action

Adds validation check for candidates setting profile

---

contracts/TestHelpers.ts
contracts/eosdactokens/eosdactokens.cpp
contracts/stakevote/stakevote.cpp
contracts/stakevote/stakevote.hpp
contracts/stakevote/stakevote.test.ts

The bug is most likely caused by an incorrect calculation in collectwts. When the user has a staketime set that differs from the default, collectwts would not take this into account, leading to wrong initial values. This PR:
- Fixes collectwts (see above)
- adds an assert parameter to collectwts to aid in debugging
- Improves several error messages to be more helpful to the user and in potential future debugging
Deployment instruction: In order to fix the bug in mainnet, the new version of the contract compiled with DEBUG flag must be deployed and collectwts must be run for all dacs.

Dev 2659 bug unstake vp doesnt works properly

---

contract-shared-headers/daccustodian_shared.hpp
contracts/daccustodian/privatehelpers.cpp
contracts/stakevote/stakevote.cpp
contracts/stakevote/stakevote.test.ts

This PR fixes an "invalid unsigned subtraction" error that may occur when calling eosdactoken::staketime caused by rounding differences.

Fix invalid unsigned subtraction in eosdactoken::staketime

---

contracts/dacproposals/dacproposals.test.ts
contracts/msigworlds/msigworlds.hpp
contracts/stakevote/stakevote.test.ts

This PR
* allows the referendum contract to propose proposals without being a custodian'
* updates tests to prevent duplicate transaction errors

Demzne 1123 eosdac fix tests after recent changes

---

contract-shared-headers/daccustodian_shared.hpp
contracts/daccustodian/voting.cpp

So we can run it after deployment to update the decayed votes index

make migraterank accessible in debug build

---

contract-shared-headers/daccustodian_shared.hpp
contracts/daccustodian/daccustodian.cpp
contracts/daccustodian/daccustodian.test.ts
contracts/daccustodian/migration.cpp
contracts/daccustodian/newperiod_components.cpp
contracts/daccustodian/registering.cpp
contracts/stakevote/stakevote.test.ts
package.json

This PR
- Renames the field total_vote_power to rank and re-uses it to store the rank of the candidate at time of newperiod
- Updates daccustodian and stakevote tests to account for the above
- Adds a unit test for the rank calculation to the stakevote tests
This allows the UI to display the rank data for both candidates and custodians.

Demzne 1131 copy rank over to custodians in newperiod

---

contract-shared-headers/daccustodian_shared.hpp
contracts/daccustodian/daccustodian.cpp
contracts/daccustodian/daccustodian.test.ts
contracts/daccustodian/debug.cpp
contracts/daccustodian/external_observable_actions.cpp
contracts/daccustodian/migration.cpp
contracts/daccustodian/privatehelpers.cpp
contracts/daccustodian/voting.cpp

This PR changes the vote decay implementation to a more robust algorithm. 
The new field `running_weight_time` needs to be `uint128_t` as `uint64_t` would potentially not be large enough to hold expected values. That's why the existing `gap_filler` field cannot be reused for this and we need to migrate the candidates table.
Migration steps:
1. Compile code with `yarn build -p daccustodian -DMIGRATION_STAGE_1 -DDEBUG` and deploy
2. Enable maintenance mode by executing the ACTION `maintenance(true)`.
3. Execute `migrate1(dac_id)` action for all DACs to move all data from candidates table to candidates2 temp table.
4. Compile code without MIGRATION_STAGE_1 flag (only with DEBUG) like this: `yarn build -p daccustodian -DDEBUG` and deploy
5. Execute `migrate2(dac_id)` action for all DACs to …

Demzne 1187 fix avg vote time stamp pushed into the future error

---

.gitignore
contracts/stakevote/stakevote.cpp
contracts/stakevote/stakevote.hpp
contracts/stakevote/stakevote.test.ts
debugging/index.js
debugging/package.json

This PR:
* Adds a debugging project (javascript). The first script can be used to verify the the voting weights in the vote_weights table on mainnet. It prints out all incorrect values (if any).
* Fixes the problem that was causing the INVALID_WEIGHT_DELTA error message for some users. The problem was caused by rounding differences when accumulating all stake changes. The problem is fixed by calculating the avg_vote_weight directly from the amount staked (same as collectwts) instead of accumulating the deltas.

Dev 3091 error invalid weight delta update when trying to unstake vote power on kavian

---

contracts/dacproposals/dacproposals.test.ts
contracts/referendum/referendum.cpp
contracts/referendum/referendum.hpp
contracts/referendum/referendum.test.ts

Some cleanups to the referendum contract including:
* Change the enums from being numbers to being eosio::name types to be more human-readable
* Added a clean up for the votes that have been removed during the update of stake voting.
* Updated the check_transaction_authorization  internal action to stop using an internal action.

Refactors for the referendum contract to be more usable for the community

---

contracts/eosdactokens/eosdactokens.test.ts

I forgot to update the tests after we reverted the staketime code change

update test after code revert  

---

.gitmodules
contract-shared-headers/daccustodian_shared.hpp
contract-shared-headers/dacdirectory_shared.hpp
contract-shared-headers/eosdactokens_shared.hpp
contracts/dacdirectory/dacdirectory.hpp
contracts/dacescrow/dacescrow.hpp
contracts/dacproposals/dacproposals.hpp
contracts/referendum/referendum.hpp
contracts/safemath/safemath.cpp
contracts/stakevote/stakevote.hpp

This switches over to the new contracts-common helper repository instead of safemath

Demzne 1141 consolidate common contract helpers into safemath and rename it to contracts common

---

contracts/referendum/referendum.cpp

This should be done via a reference to the found ref in the cancel action.

Fix to the referendum contract to erase referenda

---

contracts/referendum/referendum.cpp
contracts/referendum/referendum.hpp

Quick PR that cleans up empty vote records after the clean function.
All tests still pass.
Also includes a small clean up of an internal function to remove needed params.

Removes empty vote records during the clean action.

---

contract-shared-headers/daccustodian_shared.hpp
contracts/TestHelpers.ts
contracts/daccustodian/config.cpp
contracts/daccustodian/daccustodian.test.ts
contracts/daccustodian/newperiod_components.cpp

The elected custodians are written to a pending table before the new custodians are brought to power after the pending period and new period is called again.
BTW. The test pass when run just for the daccustodians tests.
┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/86930dqqm) by [Unito](https://www.unito.io)

Updates to the DAO election process to include a configurable pending time

---

contracts/eosdactokens/eosdactokens.cpp
contracts/eosdactokens/eosdactokens.hpp

Adds a new ACTION `chngissuer` that requires `get_self()` permission that changes the issuer of all planetary tokens to the given account name.
Has been tested [here](https://github.com/Alien-Worlds/alienworlds-contracts/pull/148/commits/ac71251b22775ce0dd8146a952e3add0779f2953) and it works.
┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/86931gk6u) by [Unito](https://www.unito.io)

action to change issuer for all planet tokens

---

.gitignore
package.json

This is only relevant for the planet token contract.
The value is injected from a git ignored file named `.magic_key_value`
┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/86936cpty) by [Unito](https://www.unito.io)

Change the compiling step to inject the magic value 

---

contracts/referendum/referendum.cpp
contracts/referendum/referendum.test.ts

to allow the DAOs to update the config per DAO. 
But to be safe, I have disabled the binding execution of MSIGs since this could bypass the DAO MSIG execution with low threshold configs.
┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/8693axq1x) by [Unito](https://www.unito.io)

Update to the referendum contract

---

contracts/dacproposals/dacproposals.cpp

Quick change to to access for the new permissions

Locks down the set prop fee and min duration to get_self() for dacpropoals.

---

contract-shared-headers/daccustodian_shared.hpp
contracts/TestHelpers.ts
contracts/daccustodian/config.cpp
contracts/daccustodian/daccustodian.test.ts
contracts/daccustodian/registering.cpp
contracts/dacproposals/dacproposals.cpp
contracts/dacproposals/dacproposals.hpp
contracts/dacproposals/dacproposals.test.ts

Adds:
* whitelists for daccustodians for candidates
* config to indicate if a DAO requires verified candidates
* whitelist for worker proposals proposers
* management actions to add/remove/update accounts on the added whitelists
Updated tests for the new logic and ensured they pass.

Whitelist for daccustodian and dacpropsals

---

contracts/eosdactokens/eosdactokens.cpp

This should allow the token issuer to:
* Receive transferlocked DAO tokens.
* Burn transferlocked DAO tokens.
Both of these are required to be able to stake TLM into DAO tokens and unstake from DAO tokens

Fix to token contract for locked tokens

---

contracts/TestHelpers.ts
contracts/daccustodian/daccustodian.test.ts
contracts/daccustodian/registering.cpp
contracts/dacescrow/dacescrow.cpp
contracts/dacescrow/dacescrow.hpp
contracts/dacproposals/dacproposals.cpp
contracts/dacproposals/dacproposals.hpp
contracts/dacproposals/dacproposals.test.ts
contracts/referendum/referendum.test.ts
contracts/safemath/safemath.test.ts
contracts/stakevote/stakevote.test.ts

These changes are small changes to the worker proposal flow after reviews with the UI.
* Arbiters should be paid for both approved and disputed proposals (previously it was only disputed ones)
* When a proposal is completed it should not be removed immediately so that it can still be seen the UI
* Added an action to remove completed proposals at a later time.
* Added Completed state for proposals.
Sorry, I have not updated the tests for this change.

Worker proposal changes

---

contract-shared-headers/daccustodian_shared.hpp
contracts/daccustodian/config.cpp
contracts/daccustodian/daccustodian.test.ts
contracts/daccustodian/newperiod_components.cpp

Changes to the claim budget action:
* The amount claimed is based on a configured amount if there is sufficient balance for the claim amount
* Otherwise distribute a configured percentage to the worker proposal funds account
* And send the remaining balance to the spending account.
This will have the effect of leaving the spending percentage setting redundant.
Also, there is a small change to the max number of custodians allowed in the config changes.

Change claim budget to linear calc style

---

contracts/dacproposals/dacproposals.cpp

This is to prevent anyone from becoming an active arbiter without our explicit permission.
With this enabled, after a user is KYC'd we would then update their rating to a value greater than 0 for it to allow proposals to be made.

Require arbs to have a rating > 0 to be used

---

contracts/dacproposals/dacproposals.cpp
contracts/dacproposals/dacproposals.test.ts

Should be a simple change to prevent the DAOs changing their own WP config.
I've updated the tests but I got an error when trying to run the tests `access violation`. Could be a local issue...

Prevent daos change wp config

---

check_proxy_votes.sh
contract-shared-headers/daccustodian_shared.hpp
contracts/daccustodian/debug.cpp
contracts/daccustodian/registering.cpp
debugging/check_orphaned_votes.js
debugging/rebuild_vote_weights/1_start_vote_weight_rebuild.sh
debugging/rebuild_vote_weights/2_rebuild_vote_weights.sh
debugging/rebuild_vote_weights/3_finish_vote_weight_rebuild.sh
debugging/rebuild_vote_weights/vote_weight_rebuild_procedure.md

1) Adds debug helpers `clrprxvotes` and `clrproxies` to remove all proxy votes and registered proxies
2) 3 scripts to rebuild the vote weights
- 1_start_vote_weight_rebuild.sh 
- 2_rebuild_vote_weights.sh 
- 3_finish_vote_weight_rebuild.sh
1) builds the contract with DEBUG flag
2) deploys it
3) switches the contract into maintenance mode
When no additional command line arguments are given, it automatically retrieves all dac ids from the `index.worlds` contract and loops over them. If only specific dacs should be processed, the dac id can be given as command line parameter. In this case, only the specified dac id will be processed.
1) Runs `clrprxvotes` to remove all proxy votes
2) Runs `clrproxies` to remove all proxies that have been unintentionally registered
3) Calls `resetstate` and …

add procedure and scripts to safely rebuild vote weights
